language: node_js
node_js:
  - "6"
services: mongodb
after_success:
  - cd docs
  - git init
  - git commit -a -m "Travis Deploy"
  - git push -f -q https://$GITHUB_TOKEN@github.com/function-x/Orange-Juice-Docs.git master
